#!/bin/bash
#
# Copyright 2015-2025, Dan Landon
#
# Permission is granted to use this software for personal, educational, or internal use only.
#
# Commercial use, redistribution, or modification of this software or any derived works is strictly prohibited without prior written permission.
#
DOCROOT=`grep -Po '^chdir = \K.*' /etc/php-fpm.d/www.conf 2>/dev/null`
if [ -z ${DOCROOT} ];then
	DOCROOT="/usr/local/emhttp"
fi

logger "Enabling Syslog filter..." -t"enhanced.log"
${DOCROOT}/plugins/enhanced.log/scripts/rc.enhanced.log
