#!/bin/bash
#
DOCROOT=`grep -Po '^chdir = \K.*' /etc/php-fpm.d/www.conf 2>/dev/null`
if [ -z ${DOCROOT} ];then
	DOCROOT="/usr/local/emhttp"
fi

logger "Enabling Syslog filter..." -t"enhanced.log"
${DOCROOT}/plugins/enhanced.log/scripts/rc.enhanced.log